export const FETCH_ACHIEVEMENTS_REQUEST = 'FETCH_ACHIEVEMENTS_REQUEST';
export const FETCH_ACHIEVEMENTS_SUCCESS = 'FETCH_ACHIEVEMENTS_SUCCESS';
export const FETCH_ACHIEVEMENTS_FAILURE = 'FETCH_ACHIEVEMENTS_FAILURE';
export const SET_QUERY = 'SET_QUERY';
export const INCREMENT_OFFSET = 'INCREMENT_OFFSET';
export const RESET_DATA = 'RESET_DATA';
